local Language = require("core.lang")
local logger = require("core.logger").new("lua")

Language.new("lua")
    :spaces(4)
    :width(100)
    :register()

Language.new("go")
    :tabs(4)
    :preserve_indent()
    :width(100)
    :register()

Language.new("sh")
    :spaces(4)
    :preserve_indent()
    :width(100)
    :register()

Language.new("nix")
    :spaces(2)
    :preserve_indent()
    :width(100)
    :register()
